keys:
  - &user_core age1lehvxg7l88c565huaqnk32shnn39k90ujmm58hew4rvugfwmhv2q22qle9
  - &host_powerhouse age1ntqkell77ru2zv87yfyheprw00zxwdy4au6ev3frmc7qq9tmm4zqjdy8ty
  - &host_turbine age1kh6w6v9zu6ahrddlsl47rypr7wtlht94hj6h2p9sqnavpujsvaqs2ghtve
  - &host_vm age1dr3ecjsnv5azmeq63764md7ag04kuyyzc8w8yx60u4v5dfndxpasyrnp4t

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_core
        - *host_powerhouse
        - *host_turbine
        - *host_vm