name: Setup Nix Environment
description: 'Reusable workflow to setup Nix environment with flakes support'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            show-trace = true
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nix-community
          # Note: For private caches, add authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      - name: Verify Nix setup
        run: |
          echo "✅ Nix installed successfully"
          nix --version
          echo "✅ Flakes support enabled"
          nix flake --help > /dev/null && echo "Flakes: OK" || echo "Flakes: FAILED"
      
      - name: Check flake syntax
        run: |
          echo "🔍 Checking flake syntax..."
          nix flake check --no-build
          echo "✅ Flake syntax is valid"
      
      - name: Enter development shell
        run: |
          echo "🚀 Entering development shell..."
          nix develop --command bash -c "
            echo 'Development environment ready!'
            echo 'Available tools:'
            command -v just >/dev/null && echo '  ✅ just' || echo '  ❌ just'
            command -v alejandra >/dev/null && echo '  ✅ alejandra' || echo '  ❌ alejandra'
            command -v nix >/dev/null && echo '  ✅ nix' || echo '  ❌ nix'
            echo 'Running just help:'
            just help || echo 'just help failed'
          "