name: Setup Nix Environment
description: 'Reusable workflow to setup Nix environment with flakes support using Determinate Systems'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          extra-conf: |
            experimental-features = nix-command flakes
            show-trace = true
      
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Verify Nix setup
        run: |
          echo "✅ Nix installed successfully"
          nix --version
          echo "✅ Flakes support enabled"
          nix flake --help > /dev/null && echo "Flakes: OK" || echo "Flakes: FAILED"
      
      - name: Check flake syntax
        run: |
          echo "🔍 Checking flake syntax..."
          nix flake check --no-build
          echo "✅ Flake syntax is valid"
      
      - name: Enter development shell
        run: |
          echo "🚀 Entering development shell..."
          nix develop --command bash -c "
            echo 'Development environment ready!'
            echo 'Available tools:'
            command -v just >/dev/null && echo '  ✅ just' || echo '  ❌ just'
            command -v alejandra >/dev/null && echo '  ✅ alejandra' || echo '  ❌ alejandra'
            command -v nix >/dev/null && echo '  ✅ nix' || echo '  ❌ nix'
            echo 'Running just help:'
            just help || echo 'just help failed'
          "